import './globals.css'
import { IBM_Plex_Sans } from 'next/font/google'

const IBM = IBM_Plex_Sans({ subsets: ['latin'], weight: ['400','700'] })

export const metadata = {
  title: 'Multi Form',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={IBM.className}>{children}</body>
    </html>
  )
}
