import './globals.css'
import { Hepta_Slab } from 'next/font/google'

const hepta_slab = Hepta_Slab({ subsets: ['latin'], weight: ["400"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={hepta_slab.className}>{children}</body>
    </html>
  )
}
